
### updates an existing patient entity
PUT http://localhost:8080/api/patients/updatePatient/123e4567-e89b-12d3-a456-426614174002
Content-Type: application/json
Accept: application/json

{
  "name": "Aman k",
  "email": "aman@example.com",
  "address": "123 Main St, Springfield",
  "dateOfBirth": "1985-01-13"
}
